voxpupuli/puppet-zabbix

- manifests/params.pp
- manifests/server.pp
this is needed because the EPEL Packages using zabbixsrv as config owner
> allow custom  owner and group for zabbix server config,

- manifests/params.pp
The default config path in params.pp was missing a “d” after “agent”.
> Fix name of agent config file in params.pp

- .travis.yml
- README.md
- Rakefile
- manifests/agent.pp
- manifests/database.pp
- manifests/database/mysql.pp
- manifests/database/postgresql.pp
- manifests/init.pp
- manifests/javagateway.pp
- manifests/params.pp
- manifests/proxy.pp
- manifests/repo.pp
- manifests/server.pp
- manifests/web.pp
You have this chunk of code in `zabbix::web`
```puppet
if $manage_repo {
if ! defined(Class['zabbix::repo']) {
class { 'zabbix::repo':
zabbix_version => $zabbix_version,
}
}
} # END if $manage_repo
```
but nothing that ensures it runs before the this chunk in the same file:
```puppet
default : {
package { "zabbix-web-${db}":
ensure  => $zabbix_package_state,
before  => [
File['/etc/zabbix/web/zabbix.conf.php'],
Package['zabbix-web']
],
require => Class['zabbix::repo'],
}
```
This causes the following error: `Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid relationship: Package[zabbix-web-mysql] { require => Class[Zabbix::Repo] }, because Class[Zabbix::Repo] doesn't seem to be in the catalog`
I see how to fix this and will be submitting a pull request shortly …
> setting manage_repo to false breaks server install

- lib/puppet/provider/zabbix_host/ruby.rb
API docs say that ip must not be null.
https://www.zabbix.com/documentation/2.4/manual/api/reference/hostinterface/object#host_interface
> This resolves dj-wasabi/puppet-zabbix#37.

- manifests/web.pp
This works for me more correctly, otherwise accessing the / keeps you on http:// and when POST'ing you get a weird 2nd login screen.
> Correctly rewrite the root when using SSL, fixes #47

- manifests/agent.pp
Fix agent listenip construct to be the same as in proxy.pp. This fixes a bug (== vs != or defined vs undefined) and style.
> Fix agent listenip

- manifests/params.pp
Some mistakes in params.pp for zabbix proxy (mysql)
> Fix in params.pp with default parameter of zabbix proxy for ubuntu

- manifests/agent.pp
- manifests/web.pp
Sorry previous fix contained error
> Fix with previous fix with listenip

- manifests/init.pp
Without this commit, the manage_repo in the main class is not doing
anything.
This commit fixes that by explicitely passing the parameter to the
zabbix::repo class.
See also GH-64 for a different way of solving this
> Fix manage_repo parameter on the zabbix class

- manifests/repo.pp
Latest version of puppetlabs/apt module shows warning on every puppet run (Warning: /Apt_key[Add key: 79EA5ED4 from Apt::Source zabbix]: The id should be a full fingerprint (40 characters), see README.) if using a short key so this update includes the full 40 character key.
See Issue #61
> Update apt key to full 40characters

- manifests/web.pp
Currently it's not possible to manage vhosts in Apache 2.4. The module is using deprecated functions that only work for 2.2. This commit solves that and keeps it backwards compatible.
> bugfix for vhosts in apache 2.4

- manifests/agent.pp
- manifests/params.pp
For example if userparameter configs is managed via VCS repo. Default value is set to "true", as was in original implementation.
> Allow to not purge include dir. 

- lib/puppet/provider/zabbix.rb
- lib/puppet/provider/zabbix_host/ruby.rb
- lib/puppet/provider/zabbix_template/ruby.rb
- lib/puppet/type/zabbix_host.rb
- lib/puppet/type/zabbix_template.rb
- manifests/agent.pp
- manifests/params.pp
- manifests/resources/agent.pp
- manifests/resources/template.pp
- manifests/resources/web.pp
- manifests/template.pp
Implemented zabbix templates import.
Import is idempotent, template being imported is compared with template with the same name exported from zabbix server. At this point there is no template destroy option.
Also pull request include option to create hostgroup if it is missing, which defaults to true in params.
> import templates and create hostgroup if missing

- manifests/agent.pp
This will fix issue with RHEL7 servers having "eno167800..." names for interfaces
> Add "eno*" to interface name matching

- manifests/agent.pp
- manifests/init.pp
- manifests/javagateway.pp
- manifests/proxy.pp
- manifests/server.pp
- manifests/web.pp
All classes which call zabbix::repo should pass manage_repo and zabbix_version to zabbix::repo.
To prevent double includes the classes will check if zabbix::repo has already been included.
Instead of checking if the zabbix::repo class should be included (if $manage_repo) the class will be included either way and zabbix::repo will decide if it manages the repositories.
> Pass manage_repo and zabbix_repo to repo.pp and prevent double include

- manifests/params.pp
I fixed the path to fping for Debian system.
Test on :
- 8
- 7
- 6 
Regards.
> Fping wrong path in debian

- manifests/repo.pp
- metadata.json
this is a normal centos fork, we just need to adjust the repo detection
for this module to work:
```
operatingsystem => CloudLinux
operatingsystemrelease => 6.6
```
> add support for CloudLinux

- manifests/params.pp
- manifests/repo.pp
- metadata.json
- use yum variables in repo files ($releasever and $basearch)
- fix $releasever for PSBM
- switch the case for the repos to $::osfamily
- use one repo for all debian like OSes
- use one repo for all RHEL like OSes
- Update sid regex to not exclude jessie ( jessie is now present on the mirror)
> refactoring of repo.pp

- manifests/params.pp
- manifests/resources/agent.pp
- manifests/server.pp
- templates/zabbix_server.conf.erb
In Zabbix 2.4 added parameter for SSL client certificate. 
SSLCertLocation and SSLKeyLocation
More info 
https://www.zabbix.com/documentation/2.4/manual/appendix/config/zabbix_server
> Added supporting new Zabbix params

- manifests/web.pp
set the url to inherit from params in order to ease use for hiera, has been done to fix the following error while configuring the url via hiera:
puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Could not intern from text/pson: Could not intern from data: Could not find relationship target "Apache::Vhost[]"
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
> Generalise the zabbix_url

- manifests/agent.pp
Make it possible to set an tap0 or tun0 (OpenVPN interfaces) interface as listenip.
> tap0 or tun0 (OpenVPN interfaces) interface as listenip

- manifests/params.pp
- manifests/web.pp
This adds the param apache_php_max_input_vars to the zabbix::web class.
It will allow us to configure the amount of max input vars for GET/POST
requests. On large installations you need 2000 or more vars on mass
updates. 1000 is the default value on CentOS which gets set in the
zabbix::params.pp
> enable apache_php_max_input_vars

- templates/zabbix_server.conf.erb
SSLCertLocation and SSLKeyLocation were introduced with 2.4 and aren't compatible with 2.2, resulting in the server refusing to start due to unknown options.
https://www.zabbix.com/documentation/2.4/manual/introduction/whatsnew240#ssl_verification_and_authentication_options
> fixed SSL server template options for 2.2

- templates/zabbix_agentd.conf.erb
server active gives errors if used on agents that aren't using active agent calls, this prevents active check configuration update from [127.0.0.1:10051] started to fail (cannot connect to [[127.0.0.1]:10051]: [111] Connection refused) from occurring
> allow serveractive to be optional

- manifests/params.pp
to prevent  10832:20160120:225723.336 active check configuration update from [127.0.0.1:10051] started to fail (cannot connect to [[127.0.0.1]:10051]: [111] Connection refused) from occurring on agents
> Allow agent_serveractive value to be blank

- lib/puppet/provider/zabbix_template_host/ruby.rb
- lib/puppet/type/zabbix_template_host.rb
This new type can be used to link/unlink template to the host. zabbix_host
provide a way to assign list of templates while creating the host. But in
a scenario where:
* One need to add zabbix_host from agent setup code
* Link appropriate templates from the service setup code. For example, mysql server
deployment code can use below code to link the template "Template App MySQL" to the host.
```
zabbix_template_host{"Template App MySQL@${::hostname}": }
```
> Added zabbix_template_host type

- lib/puppet/provider/zabbix_application/ruby.rb
- lib/puppet/type/zabbix_application.rb
Example:
Zabbix_application {
zabbix_url => 'zabbix_server1',
zabbix_user => 'admin',
zabbix_pass => 'zabbix',
}
zabbix_application{"app1":
ensure   => present,
template => 'template1',
}
Note: It Raise exception on deleting an application which is a part of used template.
> Type to manage zabbix application

- manifests/proxy.pp
Hi,
thank you for the quick fixing of the issue  Database is always managed #153 
I tried running puppet fix the fix but got:
`Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install zabbix-proxy-' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package zabbix-proxy
Error: /Stage[main]/Zabbix::Proxy/Package[zabbix-proxy-]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install zabbix-proxy-' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package zabbix-proxy`
After a quick look into the fix, I saw that there part where db variable is set was not reachable …
> Update proxy.pp, fix Error: ...install zabbix-proxy- ..

- .travis.yml
- manifests/agent.pp
- manifests/database/mysql.pp
- manifests/database/postgresql.pp
- manifests/proxy.pp
- spec/classes/agent_spec.rb
- spec/classes/database_mysql_spec.rb
- spec/classes/database_postgresql_spec.rb
- spec/classes/database_spec.rb
- spec/classes/javagateway_spec.rb
- spec/classes/proxy_spec.rb
- spec/classes/repo_spec.rb
- spec/classes/server_spec.rb
- spec/classes/userparameter_spec.rb
- spec/classes/web_spec.rb
- templates/zabbix_server.conf.erb
This is an update to the Travis CI configuration and a rewrite of all rspec tests that standardizes them using the same layout. It also includes the fixes to the code required to get the rspec tests to pass with Puppet 3 and 4.
It does remove Puppet 2.7 from the test matrix. 2.7 is no longer supported and rspec generates a ton of failures that cannot be fixed without massive rewrites to the code. I believe this is fine, but it is up to you to accept it or not.
Fixes #160
> Travis CI setup: ensure all rspec tests pass

- manifests/database/mysql.pp
- manifests/database/postgresql.pp
- templates/zabbix_server.conf.erb
I've prepared a fix for version 3.0. It looks like guys from Zabbix have changed package structure with sqls - now there's only a single file in an upper directory.
I also needed to adjust server config template. Maybe it's not the most elegant solution, but it works.
> Adjust server config and databases sqls for 3.0

- lib/puppet/type/zabbix_application.rb
- lib/puppet/type/zabbix_hostgroup.rb
- lib/puppet/type/zabbix_template_host.rb
- lib/puppet/type/zabbix_userparameters.rb
These little changes allow puppet to find required files.
However my ruby skills are limited and I currently can't estimate, if `puppet/provider/*` also needs updates.
> Make types runnable in puppet 4

- manifests/repo.pp
will run on EL 6 library as EL 7 isn't supported by Amazon Linux and Amazon Linux doesn't have systemd
> updated to include Amazon Linux

- metadata.json
Arch is a rolling release distribution, the operatingsystemrelease fact
only returns the current booted kernel. Relying on that isn't useful
here.
> add Arch Linux to metadata.json

- manifests/server.pp
- manifests/web.pp
- spec/classes/server_spec.rb
- spec/classes/web_spec.rb
two additions to make zabbix + selinux working. you maybe also need:
```puppet
Selboolean{
persistent  => true,
value       => 'on',
}
selboolean{'httpd_can_network_connect_db': }
selboolean { 'httpd_can_network_connect': }
```
but this is really apache specific and should be handled by the apache module or by a profile. This PR is related to https://github.com/dj-wasabi/puppet-zabbix/issues/190
> Feature selinux

- lib/puppet/provider/zabbix_host/ruby.rb
I am assuming here that `is_af?` should be `is_a?`.
> fix typo in zabbix_host provider

- manifests/userparameters.pp
This typo prevents working userparameters.
> userparameters not working.

- manifests/agent.pp
- manifests/proxy.pp
* listenip => 'eth0' was being ignored in zabbix-agentd.conf because $listen_ip was not being set when regex matched. now $listen_ip will be set to the IPaddress returned from $::ipaddress_eth0
* added option to use interface "lo" (127.0.0.1)
> Allows setting ListenIP as "lo" loopback interface.

- manifests/init.pp
Simply adds $default_vhost to the main zabbix class.
> Manage default_vhost in zabbix main class.

- manifests/proxy.pp
- spec/classes/proxy_spec.rb
Just like Zabbix server, proxy needs selboolean zabbix_can_network set to 'on'.
> Set selboolean for zabbix proxy

- .fixtures.yml
- manifests/agent.pp
- manifests/server.pp
- metadata.json
- templates/zabbix-agent-debian.init.erb
- templates/zabbix-agent-redhat.init.erb
- templates/zabbix-agent-systemd.init.erb
- templates/zabbix-server-debian.init.erb
- templates/zabbix-server-redhat.init.erb
- templates/zabbix-server-systemd.init.erb
Here I'm adding a method to check the zabbix agent/server config file defined by the user.
This fix allaws the user to specify a different config file than the standard /etc/zabbix/zabbix_[agentd|server].conf without breaking the installation.
> Fix for issue #240

- manifests/init.pp
https://github.com/voxpupuli/puppet-zabbix/issues/170
In issues #170 the parameter was added but it didn't get pass down from zabbix to zabbix::server if using Class['zabbix']
> Fix: manage database parameter not pass to zabbix::server

- lib/puppet/provider/zabbix_host/ruby.rb
- manifests/agent.pp
- manifests/server.pp
- manifests/startup.pp
- metadata.json
- spec/classes/agent_spec.rb
- spec/classes/server_spec.rb
- spec/defines/startup_spec.rb
- spec/defines/userparameters_spec.rb
Patch for https://github.com/voxpupuli/puppet-zabbix/issues/240
> Fix: select systemd for ubuntu correctly

- Gemfile
- Rakefile
Pin Rubocop version to 2.0.0+ for dependency fix
> Fix: Pin Rubocop version to 2.0.0+

- manifests/userparameters.pp
This patch makes zabbix::userparameters respect the zabbix_package_agent parameter of zabbix::agent
> Respect user provided Zabbix agent package name in userparameters

- .msync.yml
- .travis.yml
- Gemfile
this got cherry-picked from https://github.com/voxpupuli/puppet-zabbix/pull/268
> modulesync 0.12.2

- .msync.yml
- .travis.yml
- Gemfile
- manifests/agent.pp
- manifests/params.pp
- manifests/repo.pp
- manifests/server.pp
- manifests/startup.pp
- spec/classes/agent_spec.rb
- spec/classes/sender_spec.rb
- spec/classes/server_spec.rb
- spec/defines/startup_spec.rb
> modulesync 0.12.2 + Improvements

- manifests/database/mysql.pp
- manifests/database/postgresql.pp
- spec/classes/database_mysql_spec.rb
- spec/classes/database_postgresql_spec.rb
gunzip fails when the uncompressed file exists and requires a user decision which is hidden by the failing puppet run.
> don't fail if uncompressed file exists

- manifests/web.pp
- spec/classes/web_spec.rb
As explained in [https://github.com/voxpupuli/puppet-zabbix/issues/282](https://github.com/voxpupuli/puppet-zabbix/issues/282) the code for installing the php5 database package does not currently work on Ubuntu 16.04.  This is because the name has changed from "php5-${db}" to "php-${db}" in the official repos.  This pull will update it only in those instances and still use the legacy facts for determining version for backward compatibility.
> Fix for php db package name on Ubuntu 16.04

- manifests/database/mysql.pp
- manifests/database/postgresql.pp
- spec/classes/server_spec.rb
- templates/zabbix_agentd.conf.erb
- templates/zabbix_proxy.conf.erb
- templates/zabbix_server.conf.erb
A few changes to adapt module to zabbix-3.2 and higher versions.
Some of ```3.0``` strings replaced with regular expressions, some ```@zabbix_version == '3.0'``` replaced with ```@zabbix_version >= '3.0'```.
> Adapt to zabbix-3.2 and higher.

- spec/classes/agent_spec.rb
- spec/classes/database_mysql_spec.rb
- spec/classes/database_postgresql_spec.rb
- spec/classes/database_spec.rb
- spec/classes/javagateway_spec.rb
- spec/classes/proxy_spec.rb
- spec/classes/repo_spec.rb
- spec/classes/sender_spec.rb
- spec/classes/server_spec.rb
- spec/classes/userparameter_spec.rb
- spec/classes/web_spec.rb
- spec/defines/startup_spec.rb
- spec/defines/userparameters_spec.rb
> make rspec more awesome

- manifests/agent.pp
- manifests/startup.pp
The fact is confined to Linux. we need to use getvar() to ensure it
works on other Operating systems as well.
This is a preparation for any insane person that wants to add FreeBSD
support.
> use getvar to get systemd fact

- manifests/proxy.pp
- manifests/server.pp
- manifests/web.pp
- spec/default_facts.yml
> Strict variables fix for selinux_config_mode

- manifests/params.pp
When apache hasn't been evaluated `getvar('::apache::user')` should
return `undef`.
This commit attempts to address 2 issues.
1) In puppet 4 `''` (empty string) != `undef`
2) In stdlib < 4.13.0 instead of `undef`, `getvar('::apache::user')`
returns a literal string `'class ::apache has not been evaluated'`. This
is a bug that was fixed, but it's not too hard to work around.
> Default web_config_owner/group correctly

- manifests/agent.pp
See Issue #323 (Feature Request)
Added virbr interface to list of matched interfaces.  This change allows the IP address to be set from the IP address assigned to a virtual bridge network interface.  
I did not add enp.* since that would require a more substantial modification of the code in order to do correctly since the current matching only matches at the end while predictable network interface names such as enp.* actually match in two locations:  enp[0-9]+s[0-9]+
> Add virtual bridge (virbr) to the list of network interfaces that are checked when setting listenip

- templates/zabbix-agent-systemd.init.erb
> Replaced agent systemd service with official

- spec/classes/database_postgresql_spec.rb
- spec/classes/database_spec.rb
- spec/classes/proxy_spec.rb
puppet-postgresql now uses $::selinux for conditional logic
> Fix failing test due to missing selinux fact

- README.md
> update README.md so everything is rendered correctly

- manifests/params.pp
- manifests/repo.pp
Having the `include ::apt` in this module then prevents someone from defining their own instance of the apt class with custom parameters in another manifest, forcing the use of hiera to configure the apt class (unless of course this is the intention...).
> remove the include ::apt

- spec/classes/proxy_spec.rb
> migrate proxy tests to rspec-puppet-facts

- .rspec_parallel
- manifests/proxy.pp
- manifests/web.pp
- spec/classes/database_postgresql_spec.rb
- spec/classes/database_spec.rb
- spec/classes/proxy_spec.rb
We need rspec-puppet-facts for https://github.com/voxpupuli/puppet-zabbix/pull/382
> Migrate tests to rspec-puppet-facts

- README.md
- manifests/agent.pp
- manifests/params.pp
- manifests/repo.pp
- manifests/sender.pp
- manifests/server.pp
- manifests/startup.pp
- spec/acceptance/agent_spec.rb
- spec/classes/repo_spec.rb
- templates/zabbix-agent-systemd.init.erb
These are multiple bugs that I found while doing acceptance testing. The implementation is described in the individual commit messages. This fixes https://github.com/voxpupuli/puppet-zabbix/issues/398 and https://github.com/voxpupuli/puppet-zabbix/issues/397 and is based on the work from https://github.com/voxpupuli/puppet-zabbix/pull/396 and https://github.com/voxpupuli/puppet-zabbix/pull/382
> Fix rpm key handling + chaning default values depending on zabbix version

- files/zabbix-server.te
- manifests/init.pp
- manifests/params.pp
- manifests/server.pp
- manifests/startup.pp
- spec/acceptance/server_spec.rb
- spec/classes/server_spec.rb
- spec/defines/startup_spec.rb
- spec/spec_helper_acceptance.rb
- templates/zabbix-server-systemd.init.erb
> Provide acceptance tests for zabbix server

- manifests/userparameters.pp
userparameters.pp used 'zabbix' hardcoded as owner and group. Some
distributions like Arch Linux use 'zabbix-agent'.
> define owner and group via parameters

- manifests/proxy.pp
service enable is not available for RedHat-5.x.
Prior to this commit, the manifest only enabled the service for
\>Redhat-5.x, but not for other operating systems.
> Fix proxy service not being enabled

- manifests/database.pp
- manifests/params.pp
- spec/classes/database_spec.rb
Add a pg_hba rule to aways add this rule for allow zabbix server connect to database. #411
> Add pg_hba rule to allow zabbix server #411

- templates/zabbix_server.conf.erb
The SenderFrequency variable does not exist anymore in zabbix 3.4.
> Fix for Zabbix 3.4

- lib/puppet/provider/zabbix_proxy/ruby.rb
This is a fix for #334
I found a couple issues with the zabbix_proxy ruby code used for managing the proxy resources on the zabbix server. I think this is fixed in a proper way. I am not a Ruby developer, but it has fixed the issues I was experiencing with my manifests.
> Add missing proxy_mode variable to zabbix_proxy provider

- lib/puppet/provider/zabbix_template/ruby.rb
This parameter does not exist on the applications parameter. I have double checked that all the parameters are valid in this class according to the [Zabbix docs for configuration.import](https://www.zabbix.com/documentation/3.4/manual/api/reference/configuration/import) so hopefully this is the last pull request from me for now.
This fixes #449 (which I should have caught the first time around)
> Remove updateExisting from applications in zabbix template provider.

- files/zabbix-server-ipc.te
- manifests/server.pp
- spec/acceptance/server_spec.rb
> add selinux workaround for IPC in zabbix-server3.4

- manifests/web.pp
I've recently came across an issue with the old version of the zabbixapi gem:
```
Error: Could not run: Unable to activate zabbixapi-2.4.7, because json-2.0.2 conflicts with json (>= 1.6.0, ~> 1.6)
```
The most recent version, zabbixapi 3.2.1, relaxed the json dependency and works as expected (Zabbix 3.2.x, CentOS 7.4, Puppet 5.x). I'd suggest to upgrade the default version accordingly.
> upgrade default zabbixapi to 3.2.1

- manifests/agent.pp
- spec/classes/agent_spec.rb
- templates/zabbix_agentd.conf.erb
Enhancement for supporting multiple Alias-directives inside zabbix_agentd.conf.
> Support multiple zabbix_alias

- manifests/proxy.pp
- spec/classes/proxy_spec.rb
This PR allowing use of $manage_service in zabbix::proxy class.
> Using $manage_service in zabbix::proxy

- manifests/server.pp
The versioncmp in server.pp to check if it is 3.3 or greater, doesn't work. versioncmp can't return a value greater then 1. It should be greater then 0 (see: [versioncmp docs](https://puppet.com/docs/puppet/5.3/function.html#versioncmp))
And if the versioncmp did work, it couldn't have loaded the correct .te file. It has a typo in it. The file is named zabbix-server-ipc.te and not zabbix-server-ips.te.
So this code looks like it never runned on anyone's server.
> Fixed versioncmp compare and fixed typo in file zabbix-server-ips.te

- README.md
The web.pp missed these sebooleans:
- httpd_can_network_connect
- httpd_can_network_connect_db
As mentioned in issue #477
> Document needed sebooleans for httpd/zabbix-web

- lib/puppet/provider/zabbix.rb
Along the usual Zabbix user and password, the credentials are now passed on to the Zabbix api client for HTTP basic auth support.
> #476 Pass credentials for HTTP auth

- manifests/agent.pp
- metadata.json
- spec/classes/agent_spec.rb
This commit changes the behaviour if the $listen_ip argument is not
given. In that case ListenIP is omitted from the agent configuration.
Having no ListenIP in the configuration ensures the agent listens on
both IPv4 and IPv6.
Also added a spec test for the case were ListenIP is left empty.
Acceptance testing gave no errors.
Signed-off-by: Olivier van der Toorn <oliviervdtoorn@gmail.com>
> Do not guess ListenIP, fixes #473, bump stdlib to 4.19.0

- manifests/agent.pp
- spec/acceptance/agent_spec.rb
The old regex didn't match for enp0s5 for example. Other values are
possible as well. We should match for ^e*
Fixes https://github.com/voxpupuli/puppet-zabbix/issues/493
> Fix listen_ip bug and relax interface regex

- templates/zabbix-server-systemd.init.erb
Zabbix Server starts too early in the boot process :
- It can't reach its database (if remote).
- It may have missing data for all the items that require network access.
This change makes it wait until routed networking is available.
> wait for network connectivity before Zabbix Server startup

- spec/classes/server_spec.rb
- templates/zabbix_server.conf.erb
This PR is for the following issue: https://github.com/voxpupuli/puppet-zabbix/issues/468
I am sorry if the tests aren't correct and will gladly improve if pointed in the right direction.
> Support SSL parameters for web monitoring in all versions >= 2.4

- manifests/proxy.pp
- spec/classes/proxy_spec.rb
37e7173a477ca866ff6643c8dea4797db0281fc5 removed the enable option.
This commit adds it again.
https://github.com/voxpupuli/puppet-zabbix/commit/37e7173a477ca866ff6643c8dea4797db0281fc5 removed the enable option for the proxy service.
I've added it again.
> Fix missing enable for zabbix::proxy

- manifests/init.pp
The optional variable $zabbix_server_name from the ::zabbix::web class
is not exposed in the zabbix main class. Thus if the web frontend is
installed to including the main class the server name is not
configurable. This commit exposes the $zabbix_server_name in the zabbix
main class.
> Expose server name in main class, fixes #510

- manifests/javagateway.pp
- manifests/proxy.pp
- spec/classes/javagateway_spec.rb
The zabbix-java-gateways service should be enabled
> Add missing enable => true for zabbix-java-gateway

- .travis.yml
- Gemfile
- spec/spec_helper_acceptance.rb
> fix beaker support

- manifests/repo.pp
Fix typo (missing $ before variable $facts).
> Fix missing $ in repo definition for Debian sid

- manifests/agent.pp
- manifests/params.pp
- metadata.json
The agent service name is now defined in the params.pp as well since it is different on Gentoo.
It introduces variables for Gentoo. Additionally it replaces the hardcoded agent service name with one from params.pp (which is also OS dependend).
This PR does not fix the repo not bein supported on Gentoo warning. However, the agent can be used without managing the repo as well.
Fixes #531
> Add Gentoo support

- .fixtures.yml
- .travis.yml
- metadata.json
- spec/classes/web_spec.rb
> Add Puppet 6.x support

- manifests/agent.pp
- manifests/server.pp
- manifests/startup.pp
- manifests/userparameters.pp
This PR continues the Gentoo support of the puppet-zabbix module.
It fixes a few forgotten changes from `zabbix-agent` to `$servicename`. Which is sourced from `params.pp`.
In the second commit a copy is made of `zabbix-agent-systemd.init.erb` and named as `zabbix-agentd-systemd.init.erb`. I'm not sure if this is the wanted procedure, hence I left it as a separate commit. If this is not the correct procedure feel free to reject it ;)
The last commit adds `$servicename` like support to userparameters.pp.
> Gentoo service fix

- README.md
I updated the zabbix-proxy section to account for the database type error message `Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Class[Zabbix::Database]: parameter 'database_type' expects a match for Zabbix::Databases = Enum['mysql', 'postgresql', 'sqlite']` when using the example documentation that was provided.
> Fix proxy documentation

- spec/defines/startup_spec.rb
Fixes
```
Could not autoload puppet/provider/service/init: undefined method `downcase' for nil:NilClass
```
camptocamp::systemd recently got journald support.  Since it now manages
the service, not having an `operatingsystem` fact was causing
https://github.com/puppetlabs/puppet/blob/55d2f844203b391bc6d3bc07bd92ca9b7cdb9aa2/lib/puppet/provider/service/init.rb#L24
to explode.
> Fix tests by adding missing `operatingsystem` fact

- manifests/userparameters.pp
Before this commit it was possible that the configuration variables were
undef because of unincluded subclasses. This commits adds a include
directive for zabbix::userparameters which ensures that this can't
happen.
Fixes #539.
> Include zabbix::agent for better relationship ordering

- manifests/agent.pp
If zabbix::agent::hostname is configured it should also be used for
exported resources.
Fixes #563.
> Make hostname withint exported resources configurable

- manifests/agent.pp
- manifests/params.pp
- spec/classes/agent_spec.rb
For our "IoT use case" we want to completely configure a mini server during the staging process. When a technician installs the device to its final position (in a vehicle), we want to activate the monitoring agent.
This PR adds the ability to start/stop the agent and to enable/disable the agents automatic startup during boot.
--> Could someone help me writing my first rspec tests for this feature?
> Add ability to stop the agent

- manifests/web.pp
- spec/classes/agent_spec.rb
- spec/classes/database_spec.rb
- spec/classes/sender_spec.rb
- spec/classes/server_spec.rb
- spec/classes/web_spec.rb
- spec/defines/userparameters_spec.rb
Due to the release of facterdb 0.6.0 we're now testing against Gentoo as
well. This leads to a couple of errors which this commit fixes.
~Strict variable checking was disabled until
https://github.com/puppetlabs/puppetlabs-mysql/pull/1147 got merged.~ --> Merged.
> Fix rspec tests for Gentoo

- manifests/web.pp
by pinning them to zabbixapi gem version
with support for those versions
Fixes #556
> Add Zabbix 3.4 and 4.0 support

- manifests/repo.pp
- spec/classes/repo_spec.rb
Before this commit, repo_location was usable because it wasn't handle
within zabbix::repo.
Fixes #537
> Make repo_location usable

- .travis.yml
This is a preparation for an upcoming modulesync.
> update travis distro from trusty to xenial

- lib/puppet/provider/zabbix.rb
- lib/puppet/provider/zabbix_host/ruby.rb
- lib/puppet/type/zabbix_host.rb
- manifests/agent.pp
- manifests/params.pp
- manifests/resources/agent.pp
- spec/types/zabbix_host_spec.rb
- spec/unit/puppet/provider/zabbix_host/ruby.rb
- spec/unit/puppet/type/zabbix_host_spec.rb
- spec/unit/puppet/x/spec_zabbix_types.rb
This commits adds the following improvements to zabbix_host:
* Implement self.prefetch (This allows the use of `puppet resource
zabbix_host` as well as purging unmanaged zabbix_host resources)
* Implement proper setters for all properties
* Rename the `group` parameter to `groups` to allow multiple groups to
be specified
This is another change for #570.
> Implement self.prefetch for zabbix_host

- lib/puppet/provider/zabbix_hostgroup/ruby.rb
- spec/unit/puppet/provider/zabbix_hostgroup/ruby.rb
This is another change for #570.
> Implement self.prefetch for zabbix_hostgroup

- manifests/server.pp
puppet-zabbix module depends on stdlib, `ensure_resources` is already availble for usage.
My motivation for this change is global declaration that zabbix_can_network and zabbix server belongs to this global declaration.
ensure_resource allows for resource duplication as long as declaration of those resource is identical.
Also, notifying service dependency is useless IMO, as SELinux and ZBX are separate things and ZBX doesn't need to be restarted in order to make SELinux policies to be applied.
Fixes #598
> Put selboolean{'zabbix_can_network'} inside ensure_resources

- manifests/params.pp
- manifests/repo.pp
- spec/classes/repo_spec.rb
This fairly simply PR adds the ability to specify the "unsupported" repo path similar to how you can override the repo_path.  (zabbix::repo::unsupported_repo_path is the new setting)  I am using this a a temporary measure to get Zabbix running on some RHEL 8 agents before RHEL 8 is even available, but I imagine it could be useful to others who want to mirror the unsupported repo as well.  At some level I figured, you can configure one, why not the other.  =)
n/a
> Add support for specifying unsupported repo location.

- manifests/userparameters.pp
Fix minor typo than prevents the zabbix::userparameters to notify the service when a change is made.
Fixes #607
> Fix minor typo in agent_servicename param

- templates/zabbix-server-systemd.init.erb
Delete PrivateDevices attribute in systemd service template file to avoid problems with fping execution permissions. 
Fixes #609
> Delete PrivateDevices attribute in systemd service template file

- .fixtures.yml
- manifests/params.pp
- metadata.json
- spec/classes/web_spec.rb
This module was required to support EOL Puppet/Puppet Enterprise
versions. We don't support them since a long time, so we can remove the
dependency + related code.
> drop legacy puppetlabs/pe_gem dependency & cleanup code

- manifests/database/postgresql.pp
- manifests/proxy.pp
- metadata.json
`facter` 3.14 adds support for `os.name` *VirtuozzoLinux* (https://puppet.com/docs/puppet/latest/release_notes_facter.html). This means `os.name` won't resolve to *RedHat* anymore.
> add 'VirtuozzoLinux' support

- .sync.yml
- .travis.yml
This is needed because of https://github.com/docker/for-linux/issues/835
and https://github.com/moby/moby/issues/38749.
Long story short: systemd on CentOS 7.7 is broken with current versions
of Docker.
#645
> Pin CentOS acceptance tests 7.6.1810

- lib/puppet/provider/zabbix_proxy/ruby.rb
- lib/puppet/type/zabbix_proxy.rb
- manifests/proxy.pp
- manifests/resources/proxy.pp
- spec/unit/puppet/provider/zabbix_proxy/ruby.rb
- spec/unit/puppet/type/zabbix_proxy_spec.rb
The template parameter got removed because it had no function and just added additional API calls. I therefore labeled this PR `backwards-incompatible`.
This is another change for #570.
> Implement self.prefetch for zabbix_proxy

- lib/puppet/provider/zabbix_proxy/ruby.rb
- spec/unit/puppet/provider/zabbix_proxy/ruby.rb
This allows to set a `zabbix_proxy` resource to `absent`.
> Allow to delete a zabbix_proxy

- manifests/repo.pp
- metadata.json
Zabbix.com provides a repository for Raspbian Linux under http://repo.zabbix.com/zabbix/<version>/raspbian/
The puppet-zabbix module uses the fact os.name for determining the URL of the used repository which is "Debian" for Raspbian Linux. The Debian repositiry is not providing "armhf" deb packages so the installation of zabbix fails.
This patch is an if condition which sets the variable $operatingsystem to 'raspbian' if the fact os.distro.id is 'Raspbian'. Otherwise the behaviour is not modified.
This way puppet-zabbix is choosing the right repository for installing zabbix on a Raspbian Linux.
> zabbix.com repository for Raspbian Linux

- metadata.json
We don't use it directly in this module.  It *is* a dependency of at
least one of our dependencies, so it needs to remain in .fixtures.yml.
Fixes #658
> Remove concat dependency from metadata.json

- manifests/proxy.pp
Active proxies don't use `ipaddress`, `use_ip` or `port`.  Specifically,
the zabbix_proxy provider will return `nil` for these properties for
active proxies.
> Fix zabbix::proxy idempotency

- .fixtures.yml
- manifests/agent.pp
- manifests/params.pp
- manifests/startup.pp
- metadata.json
- spec/classes/agent_spec.rb
- spec/classes/database_mysql_spec.rb
- spec/classes/database_postgresql_spec.rb
- spec/classes/database_spec.rb
- spec/classes/javagateway_spec.rb
- spec/classes/proxy_spec.rb
- spec/classes/sender_spec.rb
- spec/classes/server_spec.rb
- spec/classes/web_spec.rb
- spec/defines/startup_spec.rb
- spec/defines/userparameters_spec.rb
- templates/zabbix_agentd.conf.erb
> Add zabbix-agent support on windows

- lib/puppet/provider/zabbix_proxy/ruby.rb
- spec/acceptance/zabbix_proxy_spec.rb
zbx.proxies.delete expects an array, we handed over a string. This fixes
it a adds proper tests.
> Fix type error on zabbix_proxy delete

- lib/puppet/provider/zabbix_host/ruby.rb
- lib/puppet/type/zabbix_host.rb
- manifests/agent.pp
- manifests/params.pp
- manifests/resources/agent.pp
- spec/acceptance/zabbix_host_spec.rb
- spec/types/zabbix_host_spec.rb
- spec/unit/puppet/provider/zabbix_host/ruby.rb
- spec/unit/puppet/type/zabbix_host_spec.rb
This commit adds support for defining custom macros for zabbix hosts
> Add support for defining host's macros

- spec/acceptance/zabbix_application_spec.rb
- spec/acceptance/zabbix_host_spec.rb
- spec/acceptance/zabbix_hostgroup_spec.rb
- spec/acceptance/zabbix_proxy_spec.rb
- spec/acceptance/zabbix_template_host_spec.rb
- spec/acceptance/zabbix_template_spec.rb
- spec/spec_helper_acceptance.rb
- spec/support/acceptance/cleanup_zabbix.rb
> Cleanup and fix acceptance test helper

- lib/puppet/provider/zabbix.rb
- lib/puppet/provider/zabbix_proxy/ruby.rb
- lib/puppet/type/zabbix_proxy.rb
- spec/acceptance/zabbix_proxy_spec.rb
- spec/unit/puppet/type/zabbix_proxy_spec.rb
- It is now possible to manage individual `zabbix_proxy` resource properties.
- The type has been improved to do enhanced validation of all properties.
- Switching between active and passive proxies (and vice-versa) is now supported.
- Improved acceptance tests (Thanks @baurmatt )
- Improved type unit tests.
> Improve `zabbix_proxy` type

- .sync.yml
- .travis.yml
- Gemfile
- manifests/params.pp
- metadata.json
- spec/acceptance/agent_spec.rb
- spec/acceptance/server_spec.rb
- spec/acceptance/zabbix_application_spec.rb
- spec/acceptance/zabbix_host_spec.rb
- spec/acceptance/zabbix_hostgroup_spec.rb
- spec/acceptance/zabbix_proxy_spec.rb
- spec/acceptance/zabbix_template_host_spec.rb
- spec/acceptance/zabbix_template_spec.rb
- spec/classes/agent_spec.rb
- spec/classes/sender_spec.rb
- spec/classes/server_spec.rb
- spec/classes/web_spec.rb
- spec/support/acceptance/cleanup_zabbix.rb
> Add Debian 10 support

- .sync.yml
- .travis.yml
- Gemfile
- manifests/web.pp
- spec/acceptance/agent_spec.rb
- spec/spec_helper_acceptance.rb
> modulesync 2.12.0 / zabbix::web: Allow httpd to speak to the database

- .sync.yml
- Gemfile
This is no longer needed since we don't test on those old Ruby versions anymore.
> Drop ruby < 2.3 fakefs gem dependency

- manifests/params.pp
https://www.zabbix.com/documentation/current/manual/appendix/install/db_scripts
In Zabbix 4.4 (at least 4.4.7) proper collation is enforced and various things ceases to work properly.
This PR changes default collation of database from utf8_general_ci to utf8_bin
> Change database collation to utf8_bin as it is stated in official docs

- manifests/agent.pp
- spec/classes/agent_spec.rb
This makes the zabbix::agent's manage_firewall option work when you have multiple Zabbix servers configured in the server setting.
Fixes https://github.com/voxpupuli/puppet-zabbix/issues/199
> Fix for zabbix::agent manage_firewall when multiple servers are specified

- manifests/agent.pp
- spec/classes/agent_spec.rb
This avoids setting parameters as much as possible.
hasstatus and hasrestart have defaulted to true since Puppet 2.7 so there's no need to set those.
The systemd fact is defined as $fact['service_provider'] == 'systemd' so there's no need to set that either.
Then there's AIX left. It sets it this was because it allows users to override it in site.pp via service defaults. It now only sets the service_provider and not the path. This path is set in the provider since [Puppet 4.6.0](https://github.com/puppetlabs/puppet/commit/34e45ab3f562d1029bfeaafe9a11757ea3b3e92c).
I didn't verify this and only did it by theory so review carefully.
> Reduce configuration on agent service

- lib/puppet/provider/zabbix_host/ruby.rb
- lib/puppet/type/zabbix_host.rb
- manifests/agent.pp
- manifests/resources/agent.pp
This pull request adds option to specify interface type in agent.pp, so you can create an agent that is purely SNMP/JMX/IPMI.
> Add option to specify type of interface in agent class

- manifests/web.pp
- spec/acceptance/zabbix_application_spec.rb
- spec/acceptance/zabbix_host_spec.rb
- spec/acceptance/zabbix_hostgroup_spec.rb
- spec/acceptance/zabbix_proxy_spec.rb
- spec/acceptance/zabbix_template_host_spec.rb
- spec/acceptance/zabbix_template_spec.rb
This is a re-submission of #623, because the original PR was probably abandoned.
* Re-submission of #623 (with latest version of zabbixapi)
* Rebased against latest master branch
* Bumps acceptance tests to Zabbix LTS release 4.4 (it's too early for 5.x)
Fixes #621 (Zabbix 4.2 support)
Fixes #544 (Zabbix 3.4 support)
Fixes #689 (Zabbix 5.0 support; partially, should be considered the first step)
> Bump zabbixapi version

- manifests/startup.pp
- metadata.json
- spec/acceptance/server_spec.rb
- spec/acceptance/zabbix_application_spec.rb
- spec/acceptance/zabbix_host_spec.rb
- spec/acceptance/zabbix_hostgroup_spec.rb
- spec/acceptance/zabbix_proxy_spec.rb
- spec/acceptance/zabbix_template_host_spec.rb
- spec/acceptance/zabbix_template_spec.rb
- spec/defines/startup_spec.rb
- spec/support/acceptance/prepare_host.rb
> Drop Puppet 5 support

- spec/acceptance/server_spec.rb
- spec/acceptance/zabbix_application_spec.rb
- spec/acceptance/zabbix_host_spec.rb
- spec/acceptance/zabbix_hostgroup_spec.rb
- spec/acceptance/zabbix_proxy_spec.rb
- spec/acceptance/zabbix_template_host_spec.rb
- spec/acceptance/zabbix_template_spec.rb
- spec/support/acceptance/prepare_host.rb
We rely on those packages in most tests. To be able to run them
independently, we need to manage them in the helper.
> acceptance tests: move package setup into helper

- manifests/database.pp
- metadata.json
Fixes deprecation warning.
Also increased minimum postgresql module version to when namespaced postgresql_password function was introduced.
> database: use namespaced postgresql_password function; bump puppetlabs/postgresql lower dependency 4.4.2->6.4.0

- manifests/database/mysql.pp
- manifests/database/postgresql.pp
- manifests/params.pp
- manifests/repo.pp
- manifests/server.pp
- manifests/web.pp
- spec/acceptance/agent_spec.rb
- spec/acceptance/zabbix_application_spec.rb
- spec/acceptance/zabbix_host_spec.rb
- spec/acceptance/zabbix_hostgroup_spec.rb
- spec/acceptance/zabbix_proxy_spec.rb
- spec/acceptance/zabbix_template_host_spec.rb
- spec/acceptance/zabbix_template_spec.rb
- spec/classes/database_mysql_spec.rb
- spec/classes/database_postgresql_spec.rb
- spec/classes/web_spec.rb
- spec/support/acceptance/prepare_host.rb
- templates/web/php-fpm.d.zabbix.conf.epp
Adds support for Zabbix 5.x.
Maybe more tests are needed
Depends on #742 
Fixes #731 
Closes #737 
Closes #736 
Closes #721 
Closes #715 
Closes #694
> Add support for Zabbix 5.x

- manifests/params.pp
- spec/classes/agent_spec.rb
- spec/classes/proxy_spec.rb
- spec/classes/repo_spec.rb
- spec/classes/sender_spec.rb
- spec/classes/server_spec.rb
- spec/classes/web_spec.rb
3.4 is EOL and we will remove code for it in https://github.com/voxpupuli/puppet-zabbix/pull/750
> Bump default Zabbix version on linux 3.4->5.0

- metadata.json
Increase max versions of dependency modules to allow for use of updated puppetlabs releases.
Needs https://github.com/camptocamp/puppet-systemd/pull/182.
> Module version bumps

- README.md
- lib/puppet/provider/zabbix_template/ruby.rb
- lib/puppet/type/zabbix_template.rb
- manifests/resources/template.pp
- manifests/template.pp
- spec/acceptance/zabbix_template_host_spec.rb
- spec/acceptance/zabbix_template_spec.rb
Zabbix changed templateScreens option in configurations.import API call to templateDashboards.
Source: 
5.2: https://www.zabbix.com/documentation/current/manual/api/reference/configuration/import
5.0: https://www.zabbix.com/documentation/5.0/manual/api/reference/configuration/import
(rules object)
> Fix templates importing in Zabbix 5.2+

- manifests/params.pp
- spec/classes/agent_spec.rb
- spec/classes/proxy_spec.rb
- spec/classes/server_spec.rb
When setting `logtype` to system ensure `logfile` and `logfilesize` have correct values instead of `undef`.
Chagning logtype to file could lead to non-working agent due to these values being undef, which is not obvious.
> Ensure correct logfile/logfilesize values when defaulting logtype to system

- .sync.yml
- lib/puppet/provider/zabbix.rb
- lib/puppet/provider/zabbix_template/ruby.rb
- manifests/database/mysql.pp
- manifests/database/postgresql.pp
- manifests/proxy.pp
- manifests/server.pp
- manifests/web.pp
- spec/acceptance/agent_spec.rb
- spec/acceptance/server_spec.rb
- spec/acceptance/zabbix_application_spec.rb
- spec/acceptance/zabbix_host_spec.rb
- spec/acceptance/zabbix_hostgroup_spec.rb
- spec/acceptance/zabbix_proxy_spec.rb
- spec/acceptance/zabbix_template_host_spec.rb
- spec/acceptance/zabbix_template_spec.rb
- spec/classes/database_mysql_spec.rb
- spec/classes/database_postgresql_spec.rb
- spec/classes/web_spec.rb
- spec/spec_helper.rb
- spec/support/acceptance/supported_versions.rb
Adds Zabbix 5.4 support.
zabbixapi gem doesn't have support for 5.4 version yet. 
For now I passed `ignore_version` parameter. It seems to be working fine as there aren't any API changes that would break the gem. If we don't feel comfortable merging this I may open a PR on zabbixapi repo.
Closes #773 (Thanks for pointing out!)
> Add Zabbix 5.4 support

- README.md
> Update README.md with new badges/transfer notice

- lib/puppet/provider/zabbix_host/ruby.rb
- lib/puppet/type/zabbix_host.rb
- manifests/agent.pp
- manifests/resources/agent.pp
- spec/acceptance/zabbix_host_spec.rb
Following the pull request #697 we add an hash of interface options to configure some details about SNMP.
We want to use to add SNMP host with community and other details.
Example
```
zabbix_host { 'SNMPServer':
ipaddress     => '192.168.1.1',
use_ip        => true,
port          => 161,
groups        => ['SNMP servers'],
group_create  => true,
templates     => ['Template Module ICMP Ping'],
macros        => [],
proxy         => '',
interfacetype => 2,
interfacedetails => {"version" => 2, "bulk" => 0, "community" => "public"},
}
```
Using interfacetype = 2 without details we have the error
```
{"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params.","data":"Incorrect arguments passed to function."},"id":42907}
```
No issues opened, follow pull request #697
> Added details to host network interface to configure SNMP hosts

- manifests/agent.pp
- manifests/proxy.pp
- manifests/repo.pp
- manifests/server.pp
- manifests/web.pp
- metadata.json
- spec/acceptance/agent_spec.rb
- spec/acceptance/zabbix_application_spec.rb
- spec/acceptance/zabbix_host_spec.rb
- spec/acceptance/zabbix_hostgroup_spec.rb
- spec/acceptance/zabbix_proxy_spec.rb
- spec/acceptance/zabbix_template_host_spec.rb
- spec/acceptance/zabbix_template_spec.rb
- spec/classes/server_spec.rb
- spec/classes/web_spec.rb
> Add Debian 11 support

- lib/puppet/type/zabbix_host.rb
- manifests/agent.pp
- manifests/resources/agent.pp
- spec/acceptance/zabbix_host_spec.rb
This PR follow PR #785 to ensure the host object idempotency. When interface details are empty the zabbix API returns an empty array and I need to convert it in an empty hash.
This is returned by the api call:
```json
"interfaces": [
{
"interfaceid": "36",
"type": "1",
"main": "1",
"ip": "10.10.10.1",
"port": "10050",
"useip": "1",
"details": []
}
]
```
and the error on puppet is:
```
interfacedetails changed [] to {} (corrective)
```
> Add code to ensure interfacedetails is always a hash

- manifests/params.pp
- manifests/server.pp
- spec/classes/server_spec.rb
- templates/zabbix_server.conf.erb
The options require version 5.4.
> add zabbix-server options StartReportWriters and WebServiceURL.

- manifests/params.pp
Having a default value makes it impossible to undef the parameter, since undefing leads to the default value being used.
As per [zabbix's](https://www.zabbix.com/documentation/5.0/en/manual/appendix/config/zabbix_agentd) documentation this parameter is no mandatory, so undef as default value should be okay.
#812
> Default denykey to undef

- README.md
- lib/puppet/provider/zabbix_template/ruby.rb
- lib/puppet/type/zabbix_template_host.rb
- manifests/database/mysql.pp
- manifests/database/postgresql.pp
- manifests/proxy.pp
- manifests/server.pp
- manifests/web.pp
- spec/acceptance/zabbix_application_spec.rb
- spec/acceptance/zabbix_host_spec.rb
- spec/acceptance/zabbix_hostgroup_spec.rb
- spec/acceptance/zabbix_proxy_spec.rb
- spec/acceptance/zabbix_template_host_spec.rb
- spec/acceptance/zabbix_template_spec.rb
- spec/classes/database_mysql_spec.rb
- spec/classes/database_postgresql_spec.rb
- spec/classes/web_spec.rb
- spec/support/acceptance/prepare_host.rb
- spec/support/acceptance/supported_versions.rb
Adds support for Zabbix 6.0 LTS release.
Things that may need to be added to this PR before merging:
* Ability to migrate database while updating from an non 6.x version. `/usr/share/doc/zabbix-sql-scripts/history_pk_prepare.sql` needs to be executed against the database. Haven't found a way to tackle this. Maybe we just need to add a note on the release for people to be aware?
* Zabbix 6.0 removed the ability to be able to attach Templates directly to host via the API. This automatically renders the `zabbix_template_host` unsable on Zabbix 6.0
The only way to attach Templates is via attaching them to Host Groups, so possibly a new provider is needed
Closes #814
> Add Zabbix 6.0 support

- spec/acceptance/server_spec.rb
- spec/acceptance/zabbix_application_spec.rb
- spec/acceptance/zabbix_host_spec.rb
- spec/acceptance/zabbix_hostgroup_spec.rb
- spec/acceptance/zabbix_proxy_spec.rb
- spec/acceptance/zabbix_template_host_spec.rb
- spec/acceptance/zabbix_template_spec.rb
Arch Linux is currently only supported for the zabbix-agent.
> Disable server acceptance tests on Arch Linux

- manifests/web.pp
- metadata.json
- spec/acceptance/zabbix_application_spec.rb
- spec/acceptance/zabbix_host_spec.rb
- spec/acceptance/zabbix_hostgroup_spec.rb
- spec/acceptance/zabbix_proxy_spec.rb
- spec/acceptance/zabbix_template_host_spec.rb
- spec/acceptance/zabbix_template_spec.rb
- spec/classes/repo_spec.rb
- spec/classes/web_spec.rb
- spec/spec_helper_methods.rb
Ubuntu 16.04 has been EoL since 30/04/21
> Drop EoL Ubuntu 16.04

- .github/workflows/ci.yml
- .msync.yml
- .rubocop.yml
- .sync.yml
- Gemfile
- metadata.json
- spec/classes/agent_spec.rb
- spec/classes/server_spec.rb
- spec/defines/userparameters_spec.rb
- spec/setup_acceptance_node.pp
- spec/spec_helper.rb
- spec/spec_helper_acceptance.rb
- spec/spec_helper_methods.rb
This module install gems using the `puppet_gem` provider in the gempath of the version of Ruby bundled with Puppet.  Puppet 6 bundle Ruby 2.5 which has reached EoL on 2022-04-05, and the gems the module needs depend on gems that do not offer support for this version of Ruby anymore.
This break CI and the situation has no reason to improve in the future, so stop advertising support for Puppet 6.
This PR also include:
* #834
> Drop support for Puppet 6

- REFERENCE.md
- manifests/proxy.pp
Add `database_charset` and `database_collate` parameters for `zabbix::proxy` class.
Fixes #832
> Add charset and collate parameters for zabbix::proxy

- spec/acceptance/zabbix_host_spec.rb
As mentionned in #851, the SNMP templates has been renamed upstream, this is an attempt to fix the tests
> Add/rename Linux SNMP templates for Zabbix 6.0+

- manifests/web.pp
Make sure the DirectoryIndex is configured when apache 'default_mods` are disabled:
```puppet
class { 'apache':
default_mods  => false,
}
class { 'zabbix' :
[...]
}
```
Feel free to correct me if you think it should not be in this module, but instead only in my own `profile`.
Fixes #853
> Configure DirectoryIndex by default

- manifests/database/postgresql.pp
- spec/classes/database_postgresql_spec.rb
When configuring a postgresql database that is not running on port 5432, the `.pgpass` is not correctly configured.
Then, the `exec { 'zabbix_server_create.sql':}` does not succeed as the server could not connect to the database.
> use provided database port in pgpass

- metadata.json
Update postgresql module dependency to `< 9`
> Allow latest version of the PostgreSQL module

- lib/puppet/provider/zabbix_host/ruby.rb
- lib/puppet/type/zabbix_host.rb
- manifests/agent.pp
- manifests/resources/agent.pp
- spec/acceptance/zabbix_host_spec.rb
inspired from #700
I need to authenticate with certificate in my infrastructure, this PR allow to push the configuration to the zabbix server via «storeconfigs»
As stated in #700, there is an issue with setting the PSK through the API as PSK values are write only since zabbix 5.4.  So I didn’t bother to dig deeper on this part, as I don’t require it in my infrastructure.
> Certificate authentication in zabbix_host resource

- manifests/web.pp
- metadata.json
Apache 9.0.0 release [drops](https://github.com/puppetlabs/puppetlabs-apache/pull/2329) 2.2 support. Since Zabbix has a dependency on Apache, it makes sense to remove the comparison between >= `2.4` and `2.2`, including setting the minimum dependency version for Apache to 9.0.0.
The Zabbix module breaks if you run Apache version higher than `9.0.0`, due to not being able to verify the fact.
> Remove check for Apache 2.4

- manifests/init.pp
- manifests/params.pp
- manifests/web.pp
- spec/classes/web_spec.rb
By default, the api is open to everyone.  I would like to restrict it to only the zabbix server.
I’m not sure if it should be included in this module like I suggest, or if I should manage my own apache config by disabling this module apache management  `manage_vhost => false` in `web.pp`, but I think the changes are simple enough to include in this module
My suggestion in this PR allow to add restriction to the api like so:
```puppet
class { 'zabbix::web' :
[...]
zabbix_api_access => [$facts['networking']['fqdn']],
}
```
This creates this `location` entry in apache config (or equivalent in apache 2.2):
```apache
<Location "/api_jsonrpc.php" >
Require host zabbix.example.com
</Location>
```
> Add option to restrict API access to specific hosts

- manifests/repo.pp
- spec/classes/repo_spec.rb
This change provides the correct gpgkey for RHEL family operating systems newer than version 8.
The new gpgkey works for both the "zabbix" and the "zabbix_nonsupported" repos.
This was successfully tested on RHEL 9.
Fixes #858
> Provide correct gpgkey for RHEL family, version > 8.

- README.md
- REFERENCE.md
- manifests/agent.pp
- manifests/javagateway.pp
- manifests/proxy.pp
- manifests/server.pp
- manifests/web.pp
- spec/acceptance/agent_spec.rb
- spec/acceptance/zabbix_application_spec.rb
- spec/acceptance/zabbix_host_spec.rb
- spec/acceptance/zabbix_hostgroup_spec.rb
- spec/acceptance/zabbix_proxy_spec.rb
- spec/acceptance/zabbix_template_host_spec.rb
- spec/acceptance/zabbix_template_spec.rb
- spec/classes/proxy_spec.rb
- spec/classes/server_spec.rb
- spec/classes/web_spec.rb
- spec/support/acceptance/supported_versions.rb
> Drop support for Zabbix 5.2 and 5.4 which are EOL upstream

- manifests/database/mysql.pp
- manifests/database/postgresql.pp
- spec/classes/database_mysql_spec.rb
- spec/classes/database_postgresql_spec.rb
> remove more Zabbix 5.4 special cases now that it's unsupported

- manifests/database/postgresql.pp
- manifests/proxy.pp
- manifests/repo.pp
- manifests/web.pp
- spec/acceptance/server_spec.rb
- spec/acceptance/zabbix_application_spec.rb
- spec/acceptance/zabbix_host_spec.rb
- spec/acceptance/zabbix_hostgroup_spec.rb
- spec/acceptance/zabbix_proxy_spec.rb
- spec/acceptance/zabbix_template_host_spec.rb
- spec/acceptance/zabbix_template_spec.rb
- spec/classes/database_postgresql_spec.rb
- spec/classes/repo_spec.rb
> OracleLinux fixes

- manifests/params.pp
- spec/acceptance/server_spec.rb
- spec/acceptance/zabbix_application_spec.rb
- spec/acceptance/zabbix_host_spec.rb
- spec/acceptance/zabbix_hostgroup_spec.rb
- spec/acceptance/zabbix_proxy_spec.rb
- spec/acceptance/zabbix_template_host_spec.rb
- spec/acceptance/zabbix_template_spec.rb
- spec/classes/proxy_spec.rb
- spec/classes/server_spec.rb
> increase default CacheSize to 32M, the default in 6.0 

- manifests/params.pp
- metadata.json
- spec/acceptance/server_spec.rb
- spec/acceptance/zabbix_application_spec.rb
- spec/acceptance/zabbix_host_spec.rb
- spec/acceptance/zabbix_hostgroup_spec.rb
- spec/acceptance/zabbix_proxy_spec.rb
- spec/acceptance/zabbix_template_host_spec.rb
- spec/acceptance/zabbix_template_spec.rb
- spec/classes/agent_spec.rb
- spec/classes/proxy_spec.rb
- spec/classes/sender_spec.rb
- spec/classes/server_spec.rb
> add EL9 support

- spec/classes/agent_spec.rb
- spec/classes/database_spec.rb
- spec/classes/javagateway_spec.rb
- spec/classes/sender_spec.rb
- spec/classes/server_spec.rb
- spec/classes/web_spec.rb
- spec/defines/userparameters_spec.rb
Refactoring to use structured $facts hash syntax in unit tests
> Use structured $facts hash syntax in spec tests

- spec/classes/agent_spec.rb
- spec/classes/database_mysql_spec.rb
- spec/classes/javagateway_spec.rb
- spec/classes/repo_spec.rb
- spec/classes/sender_spec.rb
- spec/classes/server_spec.rb
- spec/classes/web_spec.rb
Add unit tests to reach 100% resource coverage
> Add unit tests to reach 100% resource coverage

- REFERENCE.md
- lib/puppet/provider/zabbix_application/ruby.rb
- lib/puppet/provider/zabbix_host/ruby.rb
- lib/puppet/provider/zabbix_hostgroup/ruby.rb
- lib/puppet/provider/zabbix_proxy/ruby.rb
- lib/puppet/provider/zabbix_template/ruby.rb
- lib/puppet/provider/zabbix_template_host/ruby.rb
- lib/puppet/provider/zabbix_userparameters/ruby.rb
- lib/puppet/type/zabbix_application.rb
- lib/puppet/type/zabbix_host.rb
- lib/puppet/type/zabbix_hostgroup.rb
- lib/puppet/type/zabbix_proxy.rb
- lib/puppet/type/zabbix_template.rb
- lib/puppet/type/zabbix_template_host.rb
- lib/puppet/type/zabbix_userparameters.rb
- types/historyics.pp
fix: add documentation to satisfy linting
Fixes the following warnings that do pop up while linting:
```
[warn]: Missing documentation for Puppet type alias 'Zabbix::Historyics' at types/historyics.pp:1.
[warn]: Missing a description for Puppet resource property 'ensure' at lib/puppet/type/zabbix_host.rb:4.
[warn]: Missing a description for Puppet resource property 'ensure' at lib/puppet/type/zabbix_proxy.rb:4.
[warn]: Missing a description for Puppet resource property 'ensure' at lib/puppet/type/zabbix_template.rb:4.
[warn]: Missing a description for Puppet resource property 'ensure' at lib/puppet/type/zabbix_hostgroup.rb:6.
[warn]: Missing a description for Puppet resource property 'ensure' at lib/puppet/type/zabbix_application.rb:15.
[warn]: Missing a description for Puppet provider …
```
> add documentation to satisfy linting

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .msync.yml
- .sync.yml
- Gemfile
- spec/support/acceptance/supported_versions.rb
> gha-puppet v2

- README.md
- REFERENCE.md
- manifests/database.pp
- manifests/web.pp
- spec/acceptance/hieradata/common.yaml
- spec/acceptance/hieradata/os/RedHat/8.yaml
- spec/acceptance/server_spec.rb
- spec/acceptance/zabbix_application_spec.rb
- spec/acceptance/zabbix_host_spec.rb
- spec/acceptance/zabbix_hostgroup_spec.rb
- spec/acceptance/zabbix_proxy_spec.rb
- spec/acceptance/zabbix_template_host_spec.rb
- spec/acceptance/zabbix_template_spec.rb
- spec/classes/database_mysql_spec.rb
- spec/classes/database_spec.rb
- spec/classes/proxy_spec.rb
- spec/classes/web_spec.rb
This does the required includes for `apache` and `postgresql::server` if needed. It then uses this together with beaker-hiera (which voxpupuli-acceptance already automatically sets up for us) to reduce duplication in acceptance tests.
> Better Hiera compatibility

- manifests/params.pp
- manifests/repo.pp
- manifests/web.pp
- spec/classes/web_spec.rb
- templates/zabbix_agentd.conf.erb
- templates/zabbix_proxy.conf.erb
- templates/zabbix_server.conf.erb
we don't support 4.x anymore, so anything that's checking for versions before 5.0 can be safely removed
> remove old version comparison guards for Zabbix pre 5.0

- manifests/proxy.pp
If we don't specify the `$listenip` parameter for the zabbix proxy class its value is, by default, `undef`, which in turn causes the variable `$listen_ip` to be undefined:
https://github.com/voxpupuli/puppet-zabbix/blob/58b7688015b4b0e1a3332a3892eea8fe4a186b2a/manifests/proxy.pp#L310-L323
and here `$listen_ip` is used without being ever defined:
https://github.com/voxpupuli/puppet-zabbix/blob/58b7688015b4b0e1a3332a3892eea8fe4a186b2a/manifests/proxy.pp#L336-L343
Puppet 8 seems to be more strict than puppet 7 and errors out with the following message:
```shell
Error: Unknown variable: 'listen_ip'
```
This is how i'm using the proxy class
```ruby
class { 'zabbix::proxy':
zabbix_version       => $version,
zabbix_package_state => 'installed',
manage_resources     => true,
mode …
```
> manifests/proxy.pp: avoid undefined variable for Puppet 8 compat

- manifests/database/mysql.pp
- manifests/database/postgresql.pp
- spec/classes/database_mysql_spec.rb
- spec/classes/database_postgresql_spec.rb
- spec/classes/proxy_spec.rb
- spec/classes/server_spec.rb
This started with the goal of getting rid of /root/.pgpass and instead use environment variables, but it escalated. See individual commits for details.
> Clean up PostgreSQL DB creation logic

- REFERENCE.md
- manifests/web.pp
- manifests/zabbixapi.pp
- spec/support/acceptance/prepare_host.rb
> move zabbixapi gem installation into own class

- manifests/params.pp
- manifests/startup.pp
- metadata.json
Add support for FreeBSD only for Zabbix Agent.
Tested on FreeBSD 13.1 with puppet 7.23
> Add support for FreeBSD only for Zabbix Agent

- REFERENCE.md
- lib/puppet/type/zabbix_host.rb
- manifests/agent.pp
- manifests/params.pp
- manifests/resources/agent.pp
- spec/acceptance/zabbix_template_host_spec.rb
- spec/types/zabbix_host_spec.rb
- spec/unit/puppet/type/zabbix_host_spec.rb
These were deprecated since 7.0.0 via a4750d47cd21ed8b03722b36df0b05a3fb9ff482
> Remove deprecated zabbix_host.group, zabbix::agent::zbx_group, zabbix::resources::agent::group parameters

- manifests/params.pp
- spec/classes/agent_spec.rb
> use os.family fact to detect params

- REFERENCE.md
- manifests/init.pp
- manifests/params.pp
- manifests/proxy.pp
- manifests/server.pp
- spec/classes/proxy_spec.rb
- spec/classes/server_spec.rb
- templates/zabbix_proxy.conf.erb
- templates/zabbix_server.conf.erb
This PR adds support for the `StartODBCPollers` configuration parameter, that was introduced in Zabbix 6.0.
This parameter was already discussed in https://github.com/voxpupuli/puppet-zabbix/issues/814#issuecomment-1042347988, but a PR was never submitted, AFAICT.
> Add support for ODBC pollers in Zabbix >= 6.0

- spec/setup_acceptance_node.pp
- spec/support/acceptance/prepare_host.rb
See individual commits for details. The goal is to make the number of steps smaller.
> Reduce the size of prepare_host in acceptance tests

- metadata.json
- spec/acceptance/agent_spec.rb
- spec/acceptance/server_spec.rb
- spec/acceptance/zabbix_application_spec.rb
- spec/acceptance/zabbix_host_spec.rb
- spec/acceptance/zabbix_hostgroup_spec.rb
- spec/acceptance/zabbix_proxy_spec.rb
- spec/acceptance/zabbix_template_host_spec.rb
- spec/acceptance/zabbix_template_spec.rb
- spec/setup_acceptance_node.pp
- spec/spec_helper_methods.rb
add Debian 12 to metadata.json
skip acceptance on version 5.0 because not supported
Initial work to add Debian 12 support
> Add Debian 12 OS support

- spec/acceptance/agent_spec.rb
- spec/acceptance/server_spec.rb
- spec/acceptance/zabbix_application_spec.rb
- spec/acceptance/zabbix_host_spec.rb
- spec/acceptance/zabbix_hostgroup_spec.rb
- spec/acceptance/zabbix_proxy_spec.rb
- spec/acceptance/zabbix_template_host_spec.rb
- spec/acceptance/zabbix_template_spec.rb
- spec/support/acceptance/supported_versions.rb
Rather than duplicating the logic in every file, this introduces helpers.
> Centralize the logic which server/agent versions are supported

- spec/classes/agent_spec.rb
- templates/zabbix_agentd.conf.erb
Enable allowkey and denykey options for agent2 as they are still valid options
n/a
> Allow allowkey and denykey on agent2

- REFERENCE.md
- manifests/agent.pp
- manifests/proxy.pp
- spec/classes/agent_spec.rb
- spec/classes/proxy_spec.rb
- templates/zabbix_agentd.conf.erb
- templates/zabbix_proxy.conf.erb
Option TLSAccept in zabbix_agentd.conf accepts list of values separated with comma. But the module define tlsaccept as Enum of those three values. The string as comma separated list of values is not allowed anymore. Therefore the tlsaccept should be array of that enum and in the template the array should be joined with comma.
BTW: the same option TLSAccept is in zabbix_proxy.conf, but in the module the tlsaccept in proxy.pp is still simple string value.
Thank you.
> Support multiple values in TLSAccept

- .github/workflows/ci.yml
- manifests/repo.pp
- spec/acceptance/zabbix_host_spec.rb
- spec/acceptance/zabbix_hostgroup_spec.rb
- spec/acceptance/zabbix_proxy_spec.rb
- spec/acceptance/zabbix_template_host_spec.rb
- spec/acceptance/zabbix_template_spec.rb
- spec/classes/database_mysql_spec.rb
- spec/classes/database_postgresql_spec.rb
- spec/setup_acceptance_node.pp
- spec/support/acceptance/supported_versions.rb
Add zabbix 7.0 to CI
Zabbix has released stable lts 7.0 not tested in CI
zabbixapi gem not support zabbix 7 so it fail if you use the resource managed by it https://github.com/voxpupuli/puppet-zabbix/blob/051f24c0ec94ff1a45e75e3ad58c42eb30b41fa1/manifests/zabbixapi.pp#L15
> Add zabbix 7.0 support in CI

- .github/workflows/ci.yml
- .sync.yml
The CERN runners have way more CPU cores, which speeds up our unit tests heavily. Previously we had to filter which OSes we test on, this can be removed now.
> Unit tests: run on CERN runners

- manifests/params.pp
- spec/classes/agent_spec.rb
- spec/classes/server_spec.rb
- spec/defines/userparameters_spec.rb
Set manage_startup_script to false on OS passing acceptance test because zabbix provide correct systemd unit
Fixes #960
> Change `manage_startup_script` default to false

- manifests/params.pp
- manifests/repo.pp
- metadata.json
- spec/classes/agent_spec.rb
- spec/classes/server_spec.rb
- spec/classes/web_spec.rb
- spec/defines/userparameters_spec.rb
- spec/spec_helper_methods.rb
> Remove unsupported OS

- manifests/params.pp
- manifests/repo.pp
- manifests/server.pp
- manifests/web.pp
- metadata.json
- spec/acceptance/hieradata/family/RedHat/9.yaml
- spec/classes/agent_spec.rb
- spec/classes/database_postgresql_spec.rb
- spec/classes/javagateway_spec.rb
- spec/classes/proxy_spec.rb
- spec/classes/repo_spec.rb
- spec/classes/sender_spec.rb
- spec/classes/server_spec.rb
- spec/classes/web_spec.rb
- spec/setup_acceptance_node.pp
- spec/spec_helper_acceptance.rb
- spec/support/acceptance/supported_versions.rb
- templates/web/php-fpm.d.zabbix.conf.epp
> Remove EL7 support
