voxpupuli/puppet-zabbix

manifests/proxy.pp
templates/zabbix_proxy.conf.erb

Syntax problem in proxy.pp for CacheSize and in templates

line 350 modify casesize to cachesize #50

---

manifests/agent.pp
manifests/proxy.pp

Sorry about the previous change, that didn't work. I looked at the 'if $var == defined' construct but that isn't a valid puppet construct but I didn't know that. Puppet only knows about 'undef' of empty string ''.

Jvd w fix defined

---

README.md

Fixed small error regarding manage_resources and it's usage with classes

---

lib/puppet/provider/zabbix_hostgroup/ruby.rb
lib/puppet/type/zabbix_hostgroup.rb
lib/puppet/util/zabbix.rb

This patch contains:
* Create a provider for zabbix_hostgroup
* Moved common code from type to util/zabbix.rb, so that type code is simpler

Added zabbix_hostgroup

---

manifests/repo.pp

I was changed this to work with my AWS instances, I think that you can add this change in your code.

Added support to Amazon Linux with epel 6.

---

manifests/userparameter.pp

this should fix the lookup of hash only from the most specific level

merge of hiera hashes from entire hierarchy

---

manifests/agent.pp

Listen on all IPs if nothing specified ip or interface is set in the Agent Class.

Listen on all IPs

---

manifests/web.pp

@dj-wasabi 
Looks like I had an error sneak in when I was correcting the merge. This fixes the error. 
Sorry about that!

Fixed previous error in merge

---

lib/puppet/provider/zabbix_application/ruby.rb

It had a method created to debug, just removed it.

Removed a debug entry

---

manifests/proxy.pp

Fix for proxy sqlite support

---

README.md
manifests/sender.pp
spec/classes/sender_spec.rb

This implement #194 and provide a simple zabbix::sender class that
basically installs the required package. Plus, I've updated doc & tests.

Add Zabbix sender support

---

spec/classes/database_postgresql_spec.rb
spec/classes/javagateway_spec.rb
spec/classes/proxy_spec.rb
spec/classes/web_spec.rb

based on
https://gist.github.com/cdenneen/b587852a32895c083acf4fa7bf7f4801
provided by rnelson0

Enhance spec testing

---

lib/puppet/provider/zabbix_userparameters/ruby.rb

This prevents creation of resoruces.

Missing zabbix_url in create

---

CONTRIBUTORS

generated with
git log --format='%aN <%aE>' | sort -u

add CONTRIBUTORS from git log

---

manifests/server.pp
manifests/web.pp

This belongs to #222 and should make module run with ubuntu. I'd like to request you to extend your specs.

Make module run with ubuntu.

---

manifests/agent.pp
manifests/javagateway.pp
manifests/proxy.pp
manifests/repo.pp
manifests/sender.pp
manifests/server.pp
manifests/web.pp

Added package tagging for apt update workflow.

---

manifests/params.pp
manifests/proxy.pp
manifests/server.pp

Fix: add historyindexcachesize option to server and proxy code

---

.msync.yml
Gemfile
spec/default_facts.yml
spec/spec_helper.rb

modulesync 0.11.0

---

spec/classes/server_spec.rb

Tests for the commit that was merged earlier. Please provide feedback as I am not yet comfortable with creating tests.

Create tests for commit efad625cd87ce37fe91e708920da6a85b1f28e4b

---

.gitignore
.msync.yml
.travis.yml
Gemfile
Rakefile

modulesync 0.12.5

---

.msync.yml
.rubocop.yml
Gemfile
lib/puppet/provider/zabbix_host/ruby.rb

modulesync 0.12.7

---

manifests/params.pp
metadata.json

Add Fedora 24 support

---

CHANGELOG.md
manifests/agent.pp
metadata.json

Release 2.5.0

---

spec/defines/startup_spec.rb
templates/zabbix-agent-redhat.init.erb
templates/zabbix-server-redhat.init.erb

Fixes for #264

---

CHANGELOG.md
metadata.json

release 2.5.1

---

spec/classes/database_mysql_spec.rb

Here is mysql tests for zabbix-3.2 (as requested in #289).

Add MySQL tests for zabbix-3.2.

---

CHANGELOG.md
metadata.json

release 2.6.0

---

CHANGELOG.md
metadata.json

release 2.6.1

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
.msync.yml
.travis.yml

modulesync 0.16.4

---

CHANGELOG.md
metadata.json

release 2.6.2

---

.msync.yml
.travis.yml
Gemfile
spec/spec_helper.rb

modulesync 0.17.0

---

metadata.json

this is now a puppet 4 only module

bump required Puppet version

---

manifests/javagateway.pp
manifests/params.pp
spec/classes/javagateway_spec.rb
templates/zabbix_java_gateway.conf.erb

added javagateway timeout

---

Gemfile

This is a test for the new puppetlabs_spec_helper

bump puppetlabs_spec_helper 2.0.1->2.1.0

---

Gemfile

bump rubocop-rspec 1.10.0->1.13.0

---

manifests/database/mysql.pp
manifests/database/postgresql.pp
manifests/resources/web.pp
manifests/startup.pp
manifests/web.pp

puppet-lint: fix arrow_on_right_operand_line

---

.github/CONTRIBUTING.md
.msync.yml
.overcommit.yml
.rubocop.yml
.travis.yml
Gemfile
spec/classes/database_mysql_spec.rb
spec/classes/proxy_spec.rb
spec/classes/sender_spec.rb
spec/classes/server_spec.rb
spec/classes/userparameter_spec.rb
spec/classes/web_spec.rb
spec/defines/startup_spec.rb
spec/defines/userparameters_spec.rb
spec/unit/puppet/type/zabbix_template_spec.rb

Modulesync 0.21.0

---

manifests/params.pp
spec/classes/agent_spec.rb

update to new archlinux package name

---

Gemfile
spec/classes/javagateway_spec.rb

This got pulled out of https://github.com/voxpupuli/puppet-zabbix/pull/383

Enhance tests for javagateway

---

spec/defines/userparameters_spec.rb

migrate userparameters tests to rspec-puppet-facts

---

manifests/repo.pp
spec/classes/repo_spec.rb

add rspec-puppet-facts to repo.pp

---

.gitignore
.msync.yml
.rubocop.yml
Gemfile
spec/acceptance/nodesets/archlinux-2-x64.yml
spec/acceptance/nodesets/docker/ubuntu-16.04.yml

modulesync 0.21.3

---

manifests/repo.pp
spec/classes/repo_spec.rb

update rpm key urls to https

---

metadata.json

Update metadata.json for correct stdlib/puppet version

---

CHANGELOG.md
metadata.json

release 4.1.2

---

metadata.json

bump postgresql to allow 5.X

---

CHANGELOG.md
metadata.json

release 4.1.3

---

.rubocop.yml
.travis.yml
Gemfile

This PR is for testing the next modulesync_config update.

Update testmatrix to puppet5 + new gems

---

.msync.yml
.rubocop.yml
.travis.yml
Gemfile
Rakefile
manifests/database/mysql.pp
manifests/proxy.pp
manifests/server.pp
spec/acceptance/nodesets/docker/ubuntu-14.04.yml
spec/acceptance/nodesets/docker/ubuntu-16.04.yml
spec/classes/database_mysql_spec.rb
spec/classes/database_spec.rb
spec/classes/proxy_spec.rb
spec/classes/web_spec.rb

modulesync 1.1.0

---

manifests/params.pp
spec/acceptance/agent_spec.rb
spec/classes/agent_spec.rb
spec/classes/proxy_spec.rb
spec/classes/sender_spec.rb
spec/classes/server_spec.rb

Bump default zabbix version to 3.4 + test on it

---

lib/puppet/provider/zabbix_template/ruby.rb

This matches the api documentation now.
This fixes issue #446.

Changed image to images in template provider.

---

.msync.yml
.rubocop.yml
.travis.yml
Gemfile
Rakefile
spec/acceptance/nodesets/docker/debian-7.yml
spec/acceptance/nodesets/docker/debian-8.yml

modulesync 1.4.1

---

manifests/repo.pp

Update Debian repository public key ID

---

CHANGELOG.md
metadata.json

release 6.2.0

---

manifests/web.pp
spec/classes/web_spec.rb
templates/web/zabbix.conf.php.erb

rebase of https://github.com/voxpupuli/puppet-zabbix/pull/349

add ability to manage ZBX_SERVER_NAME in web class

---

metadata.json
spec/classes/database_mysql_spec.rb

allow camptocamp/systemd 2.X

---

CHANGELOG.md
metadata.json

release 6.3.0

---

CHANGELOG.md
metadata.json

release 6.3.2

---

.travis.yml
Gemfile

modulesync 1.9.3

---

manifests/agent.pp
manifests/database/mysql.pp
manifests/database/postgresql.pp
manifests/javagateway.pp
manifests/params.pp
manifests/proxy.pp
manifests/repo.pp
manifests/startup.pp
manifests/userparameters.pp
manifests/web.pp
spec/classes/database_postgresql_spec.rb
spec/classes/web_spec.rb
spec/defines/startup_spec.rb

get rid of useless topscope calling

---

Gemfile

install beaker-rspec 6 or newer

---

CHANGELOG.md
metadata.json

release 6.4.1

---

CHANGELOG.md
metadata.json

release 6.4.2

---

.msync.yml
.overcommit.yml
.travis.yml
Gemfile

modulesync: run acceptance tests on puppet6

---

.msync.yml

modulesync 2.0.0

---

.msync.yml
spec/spec_helper.rb

modulesync 2.2.0

---

CHANGELOG.md
metadata.json

release 6.5.0

---

manifests/proxy.pp
metadata.json

Replace is_ip_address with Puppet 4 native comparision

---

CHANGELOG.md
metadata.json

release 6.6.0

---

manifests/userparameters.pp

Add data types for zabbix::userparameters

---

CHANGELOG.md
metadata.json

release 6.7.0

---

.travis.yml

This is a test for the modulesync change at https://github.com/voxpupuli/modulesync_config/pull/529

switch acceptance tests from trusty to xenial

---

metadata.json

Allow puppetlabs/apache 4.x, puppetlabs/apt 7.x, puppetlabs/postgresql 6.x

---

.msync.yml
.sync.yml
.travis.yml
Dockerfile
Gemfile
Rakefile
manifests/database.pp
manifests/init.pp
manifests/proxy.pp
manifests/sender.pp
manifests/server.pp
spec/spec_helper.rb

modulesync 2.7.0

---

templates/zabbix-agent-systemd.init.erb
templates/zabbix-server-systemd.init.erb

add `managed by puppet` header to unit files

---

manifests/server.pp
metadata.json
spec/classes/agent_spec.rb
spec/classes/sender_spec.rb
spec/defines/startup_spec.rb

puppetlabs/mysql: allow 10.x & zabbix-server: start server after initfile is created

---

CHANGELOG.md
metadata.json

release v7.0.0

---

manifests/agent.pp
manifests/database/postgresql.pp
manifests/javagateway.pp
manifests/proxy.pp
manifests/resources/template.pp
manifests/server.pp
manifests/web.pp
manifests/zapache.pp

Explicitly use 'ensure => file' for normal file resources

---

.github/CONTRIBUTING.md
.msync.yml
.rubocop.yml
.travis.yml
Dockerfile
Gemfile
Rakefile
manifests/agent.pp
manifests/params.pp
manifests/proxy.pp
manifests/repo.pp
manifests/server.pp
manifests/userparameters.pp
manifests/web.pp
spec/classes/server_spec.rb
spec/classes/web_spec.rb
spec/spec_helper.rb
spec/unit/puppet/provider/zabbix_host/ruby.rb
spec/unit/puppet/provider/zabbix_hostgroup/ruby.rb
spec/unit/puppet/provider/zabbix_proxy/ruby.rb
spec/unit/puppet/type/zabbix_host_spec.rb
spec/unit/puppet/type/zabbix_hostgroup_spec.rb
spec/unit/puppet/type/zabbix_proxy_spec.rb
spec/unit/puppet/type/zabbix_template_spec.rb

modulesync 2.10.1

---

manifests/database.pp
manifests/params.pp
spec/classes/database_spec.rb

For PostgreSQL databases this van be used to add the
database to a custom tablespace.

Add tablespace parameter

---

manifests/init.pp

Make the tablespace parameter available in the zabbix class.

---

manifests/agent.pp
manifests/params.pp
spec/classes/agent_spec.rb
templates/zabbix_agentd.conf.erb

Add two new parameters HostInterface and HostInterfaceItem to the agent introduced in 4.4
Enhancement - N/A

Add support for HostInterface and HostInterfaceItem (4.4 Enhancement)

---

.github/CONTRIBUTING.md
.msync.yml
.rubocop.yml
Gemfile
Rakefile
spec/spec_helper.rb
spec/unit/puppet/provider/zabbix_host/ruby.rb
spec/unit/puppet/provider/zabbix_hostgroup/ruby.rb
spec/unit/puppet/provider/zabbix_proxy/ruby.rb
spec/unit/puppet/type/zabbix_host_spec.rb
spec/unit/puppet/type/zabbix_hostgroup_spec.rb
spec/unit/puppet/type/zabbix_proxy_spec.rb
spec/unit/puppet/type/zabbix_template_spec.rb

modulesync 2.12.0

---

.sync.yml
.travis.yml

Needed because of https://github.com/docker/for-linux/issues/835
Also see 8496ed38e58e65385a1ee46c7240c49985474014

Use older xenial docker image

---

spec/acceptance/agent_spec.rb

Test current version of Zabbix.

Add acceptance testing for 4.2 and 4.4

---

spec/acceptance/agent_spec.rb

This provides the version in the context and specific version support using a method.

Improve agent version handling in acceptance

---

spec/classes/web_spec.rb
templates/web/zabbix.conf.php.erb

Re-open PR #608 with added tests (sorry couldn't re-open the old one for some reason)
Adds extra support for custom SCHEMA usage in postgres, specifcally zabbix web, because right now there are no issues with zabbix-server config with custom schema

Add better postgres support

---

spec/support/acceptance/prepare_host.rb

This comment was previously in our spec_helper_acceptance.rb.
https://github.com/voxpupuli/puppet-zabbix/pull/699/files#diff-174f7dfb508155027cb4c3e9a1840591L5

[ci skip] document acceptance test helper method

---

manifests/web.pp
metadata.json
spec/acceptance/zabbix_application_spec.rb
spec/acceptance/zabbix_host_spec.rb
spec/acceptance/zabbix_hostgroup_spec.rb
spec/acceptance/zabbix_proxy_spec.rb
spec/acceptance/zabbix_template_host_spec.rb
spec/acceptance/zabbix_template_spec.rb

Drop CentOS 6 testing/support

---

spec/acceptance/server_spec.rb
spec/acceptance/zabbix_application_spec.rb
spec/acceptance/zabbix_host_spec.rb
spec/acceptance/zabbix_hostgroup_spec.rb
spec/acceptance/zabbix_proxy_spec.rb
spec/acceptance/zabbix_template_host_spec.rb
spec/acceptance/zabbix_template_spec.rb

postgres: Use UTF8 encoding and postgres 12 in acceptance tests

---

.github/workflows/ci.yml
metadata.json

Enable Puppet 7 support

---

metadata.json
spec/acceptance/zabbix_application_spec.rb
spec/acceptance/zabbix_host_spec.rb
spec/acceptance/zabbix_template_host_spec.rb
spec/support/acceptance/prepare_host.rb

This needs #756 to pass
Partially contains #755

Add Ubuntu 18.04 and 20.04 support

---

spec/acceptance/zabbix_application_spec.rb
spec/acceptance/zabbix_host_spec.rb
spec/acceptance/zabbix_hostgroup_spec.rb
spec/acceptance/zabbix_proxy_spec.rb
spec/acceptance/zabbix_template_host_spec.rb
spec/acceptance/zabbix_template_spec.rb
spec/support/acceptance/prepare_host.rb

Not super urgent, but it will make future release better tested on Debian 10.

Enable Debian 10 acceptance tests

---

.github/CONTRIBUTING.md
.github/workflows/ci.yml
.msync.yml
Dockerfile
Gemfile
spec/acceptance/zabbix_application_spec.rb
spec/acceptance/zabbix_host_spec.rb
spec/acceptance/zabbix_hostgroup_spec.rb
spec/acceptance/zabbix_proxy_spec.rb
spec/acceptance/zabbix_template_host_spec.rb
spec/acceptance/zabbix_template_spec.rb
spec/classes/database_mysql_spec.rb
spec/classes/database_postgresql_spec.rb
spec/classes/web_spec.rb
spec/support/acceptance/prepare_host.rb

modulesync 4.1.0

---

README.md
manifests/init.pp
manifests/params.pp
manifests/web.pp
spec/classes/web_spec.rb
templates/web/zabbix.conf.php.erb

Implements SAML settings as described [here](https://www.zabbix.com/documentation/current/manual/web_interface/frontend_sections/administration/authentication#advanced_settings).
Fixes #693 
Closes #720

Implement additional SAML settings

---

spec/support/acceptance/prepare_host.rb

Signed-off-by: Christos Papageorgiou <root.expert.xda@gmail.com>
Reduces acceptance tests runs by around 10-15 minutes for Debian family.

Optimize acceptance tests

---

CHANGELOG.md
Gemfile
metadata.json

Release 9.1.0

---

.github/CONTRIBUTING.md
.github/workflows/ci.yml
.msync.yml
Gemfile

Modulesync 4.2.0

---

spec/defines/startup_spec.rb

This updates the unit test for the defined resource to iterate on all
operating systems within the metadata.json

zabbix::startup: use rspec-puppet-facts

---

metadata.json

Releated to https://github.com/voxpupuli/puppet-zabbix/commit/0efe9c71172aa926977470d483ace39596fcf19f#diff-cc19578030cfe3b2ad0ea0cd8797a7af33040af8f181e641586bd7

Bump lower bound of systemd to 3.1.0

---

manifests/agent.pp
spec/classes/agent_spec.rb

Require startup script for the zabbix agent service

---

.sync.yml
spec/classes/agent_spec.rb
spec/classes/database_mysql_spec.rb
spec/classes/database_postgresql_spec.rb
spec/classes/database_spec.rb
spec/classes/javagateway_spec.rb
spec/classes/proxy_spec.rb
spec/classes/repo_spec.rb
spec/classes/sender_spec.rb
spec/classes/server_spec.rb
spec/classes/userparameter_spec.rb
spec/classes/web_spec.rb
spec/defines/userparameters_spec.rb
spec/spec_helper.rb
spec/spec_helper_methods.rb

with this change we won't run the unit tests, except for the tricky
startup defined resource, on all RHEL clones.

Run unit tests on only on major OS versions

---

manifests/web.pp
metadata.json
spec/spec_helper_methods.rb
templates/web/php-fpm.d.zabbix.conf.epp

This PR adds support for EL-8 hosts. It makes sure php-fpm is used there and adds EL-8 to the tests
Fixes #643
Closes #687

Add RedHat 8 support

---

lib/puppet/provider/zabbix_host/ruby.rb

Simple PR to address #809 
Fixes #809

set ipaddress to empty string if agent_use_ip is false

---

spec/setup_acceptance_node.pp

Ubuntu: Install lsb-release during CI

---

manifests/agent.pp
manifests/params.pp
metadata.json
spec/classes/proxy_spec.rb
spec/classes/repo_spec.rb

- Update puppet service resource options for AIX
- Set manage_choco to false by default for AIX

Add AIX 7 support

---

CHANGELOG.md
REFERENCE.md
metadata.json

Release 9.2.0

---

metadata.json
spec/acceptance/zabbix_application_spec.rb
spec/acceptance/zabbix_host_spec.rb
spec/acceptance/zabbix_hostgroup_spec.rb
spec/acceptance/zabbix_proxy_spec.rb
spec/acceptance/zabbix_template_host_spec.rb
spec/acceptance/zabbix_template_spec.rb
spec/classes/web_spec.rb

Drop EoL Debian 9 support

---

manifests/database/mysql.pp
manifests/database/postgresql.pp
manifests/web.pp
spec/classes/database_mysql_spec.rb
spec/classes/database_postgresql_spec.rb

My attempt at fixing the database schema issue
Fixes #838

New path for database schema

---

manifests/database.pp
metadata.json

This PR replace the deprecated mysql_password with mysql::password
N/A

Replace deprecated use of mysql_password

---

metadata.json
spec/spec_helper_methods.rb

Drop Debian 10 and Ubuntu 18.04 support

---

metadata.json
spec/spec_helper_methods.rb

Drop support for Windows 2012 and 2012 R2

---

manifests/web.pp
spec/acceptance/zabbix_application_spec.rb
spec/acceptance/zabbix_host_spec.rb
spec/acceptance/zabbix_template_host_spec.rb
spec/classes/proxy_spec.rb
spec/classes/repo_spec.rb
spec/classes/web_spec.rb
spec/support/acceptance/supported_versions.rb

Drop support for Zabbix 4.0

---

spec/support/acceptance/prepare_host.rb

don't call puppet multiple times in prepare host for acceptance

---

manifests/params.pp
spec/classes/agent_spec.rb
spec/classes/proxy_spec.rb
spec/classes/sender_spec.rb
spec/classes/server_spec.rb

install Zabbix 6.0 by default everywhere but EL7

---

spec/classes/proxy_spec.rb

execute zabbix::proxy tests everywhere

---

metadata.json

add support for AlmaLinux and Rocky 8 and 9

---

.fixtures.yml
manifests/agent.pp
manifests/javagateway.pp
manifests/proxy.pp
manifests/server.pp
metadata.json

puppetlabs/firewall: Require 7.x

---

.github/workflows/ci.yml
.sync.yml

drop pidfile_workaround

---

manifests/repo.pp

The repo is not available since a while and not expected to come back.
Closes: #802

drop naizvoru.com arm repo for Debian

---

manifests/repo.pp
spec/classes/repo_spec.rb

add support for arm64 Debian and Ubuntu repos

---

manifests/params.pp

use www-data on all Debian family systems, not only on Debian and Ubuntu

---

manifests/repo.pp

the default code works just fine

don't specialcase oracle in the repo config

---

manifests/params.pp
spec/classes/agent_spec.rb

Fixes: cbf95846e294aca51a3b179994d8c9ae801bd500

drop last bits of Fedora support

---

metadata.json

Update puppetlabs/postgresql to solve problem with gpg key Update puppetlabs/apache to solve problrm with puppet8 and duplicated parameter
Fixes #922

Allow puppetlabs/postgresql 10, puppetlabs/apache 12

---

spec/acceptance/agent_spec.rb
spec/acceptance/server_spec.rb
spec/acceptance/zabbix_proxy_spec.rb

Adopt shared example for indempotent test
Fixes #930

Use shared example for indempotent resource

---

README.md
templates/zabbix_agentd.conf.erb
templates/zabbix_proxy.conf.erb
templates/zabbix_server.conf.erb

Update documentation in config file
Fixes #948

Update documentation in config file
